/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const LucidePlus: typeof import('~icons/lucide/plus')['default']
  const LucideSearch: typeof import('~icons/lucide/search')['default']
}
