/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseChart: typeof import('./src/components/BaseChart.vue')['default']
    DataTable: typeof import('./src/components/partials/DataTable.vue')['default']
    DefectTable: typeof import('./src/components/DefectTable.vue')['default']
    FormPrintLabel: typeof import('./src/components/partials/FormPrintLabel.vue')['default']
    GroupedListView: typeof import('./src/components/GroupedListView.vue')['default']
    ProductionInfoDialog: typeof import('./src/components/ProductionInfoDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TreeFilter: typeof import('./src/components/TreeFilter.vue')['default']
  }
}
